version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    # Keeps the container running so you can work in the terminal
    command: sleep infinity
    networks:
      - wpi-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wpi-network

networks:
  wpi-network:
    driver: bridge

volumes:
  mysql-data: